version: '2.0'
services:
    LinuxDesktopOpenbox:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                WindowManager: openbox
        image: docker-linux-desktop:openbox
        container_name: docker-linux-desktop-openbox
        environment:
            Username: someuser
        ports:
        - "2200:22"
        - "3389:3389"
    LinuxDesktopGnome:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                WindowManager: gnome
        image: docker-linux-desktop:gnome
        container_name: docker-linux-desktop-gnome
        environment:
            Username: someuser
        ports:
        - "2200:22"
        - "3389:3389"
    LinuxDesktopXfce:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                WindowManager: xfce
        image: docker-linux-desktop:xfce
        container_name: docker-linux-desktop-xfce
        environment:
            Username: someuser
        ports:
        - "2200:22"
        - "3389:3389"
    LinuxDesktopLxde:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                WindowManager: lxde
        image: docker-linux-desktop:lxde
        container_name: docker-linux-desktop-lxde
        environment:
            Username: someuser
        ports:
        - "2200:22"
        - "3389:3389"
    LinuxDesktopMate:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                WindowManager: mate
        image: docker-linux-desktop:mate
        container_name: docker-linux-desktop-mate
        environment:
            Username: someuser
        ports:
        - "2200:22"
        - "3389:3389"